//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base_Datos.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registrarse", ReplyAction="http://tempuri.org/IService1/RegistrarseResponse")]
        void Registrarse(string nombre, string apellido, string direccion, System.DateTime fec_nac, string usuario, string contra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registrarse", ReplyAction="http://tempuri.org/IService1/RegistrarseResponse")]
        System.Threading.Tasks.Task RegistrarseAsync(string nombre, string apellido, string direccion, System.DateTime fec_nac, string usuario, string contra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loguearse", ReplyAction="http://tempuri.org/IService1/LoguearseResponse")]
        bool Loguearse(string usuario, string contra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loguearse", ReplyAction="http://tempuri.org/IService1/LoguearseResponse")]
        System.Threading.Tasks.Task<bool> LoguearseAsync(string usuario, string contra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Base_Datos.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Base_Datos.ServiceReference1.IService1>, Base_Datos.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Registrarse(string nombre, string apellido, string direccion, System.DateTime fec_nac, string usuario, string contra) {
            base.Channel.Registrarse(nombre, apellido, direccion, fec_nac, usuario, contra);
        }
        
        public System.Threading.Tasks.Task RegistrarseAsync(string nombre, string apellido, string direccion, System.DateTime fec_nac, string usuario, string contra) {
            return base.Channel.RegistrarseAsync(nombre, apellido, direccion, fec_nac, usuario, contra);
        }
        
        public bool Loguearse(string usuario, string contra) {
            return base.Channel.Loguearse(usuario, contra);
        }
        
        public System.Threading.Tasks.Task<bool> LoguearseAsync(string usuario, string contra) {
            return base.Channel.LoguearseAsync(usuario, contra);
        }
    }
}
